//
//  udkey.h
//  Blackcat
//
//  Created by haojunhua on 14-4-10.
//
//

#ifndef Blackcat_udkey_h
#define Blackcat_udkey_h

#define UDKEY_USER_TOKEN "USER_TOKEN"
#define UDKEY_USER_USERNAME "USER_USERNAME"
#define UDKEY_USER_REG_MOBILEPHONE "USER_REG_MOBILEPHONE"
#define UDKEY_USER_REG_ACTIVATECODE "USER_REG_ACTIVATECODE"
#define UDKEY_USER_REG_CODE "USER_REG_CODE"

#define LAST_RENWU_DAY "LAST_RENWU_DAY"
#define LAST_RENWU_DAY_COUNT "LAST_RENWU_DAY_COUNT"
#define LAST_KECHENG_ID "LAST_KECHENG_ID"

#define COLLECT_HANZI_COUNT  "COLLECT_HANZI_COUNT"
#define COLLECT_TUPIAN_COUNT  "COLLECT_TUPIAN_COUNT"
#define COLLECT_XINGXING_COUNT  "COLLECT_XINGXING_COUNT"
#define OVER_XINGXING_COUNT  "OVER_XINGXING_COUNT"


#define LAST_HANZI_ID  "LAST_HANZI_ID"
#define LAST_OPEN_TIMESTAMP  "LAST_OPEN_TIMESTAMP"
#define NEW_OPEN "NEW_OPEN"
#define IS_INSTALLED "IS_INSTALLED"
#define IS_SHOW_GONGKAIXIN "IS_SHOW_GONGKAIXIN"

#define PET_ENTER_MODE "PET_ENTER_MODE"

#define NEVER_OPEN_PARENT "NEVER_OPEN_PARENT"

#define USER_EXPERIENCE "USER_EXPERIENCE"

#endif
